In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib as plt
import urllib.request, json

What data we use:
  * biggest stocks from EUROSTOX50, NASDAQ and DOW (to limit input dimensionality)
  * for the last 5 years (to have growing and volaile)
  * daily oclh
Where do we get them:

In [2]:
with urllib.request.urlopen("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AD.AMS&apikey=SLQLZPOJI7PGOISP") as url:
    data = json.loads(url.read().decode())
    print(data)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'AD.AMS', '3. Last Refreshed': '2019-02-01', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2019-02-01': {'1. open': '23.0900', '2. high': '23.1500', '3. low': '22.8800', '4. close': '22.9450', '5. volume': '3522066'}, '2019-01-31': {'1. open': '23.0000', '2. high': '23.1000', '3. low': '22.6550', '4. close': '23.0200', '5. volume': '6522780'}, '2019-01-30': {'1. open': '23.4150', '2. high': '23.4200', '3. low': '23.2050', '4. close': '23.3300', '5. volume': '3114316'}, '2019-01-29': {'1. open': '23.4000', '2. high': '23.4900', '3. low': '23.3250', '4. close': '23.4000', '5. volume': '3138199'}, '2019-01-28': {'1. open': '23.2850', '2. high': '23.3700', '3. low': '23.0950', '4. close': '23.2150', '5. volume': '3750427'}, '2019-01-25': {'1. open': '23.1450', '2. high': '23.4750', '3. low': '23.0700', '4. close': '23.3850', '5. volume': '4711103'}, '2019-01-24': {'1. open': '23.0700', '2. high': '23.1150', '3. low': '22.8950', '4. close': '23.0750', '5. volume': '5334620'}, '2019-01-23': {'1. open': '22.9950', '2. high': '23.2750', '3. low': '22.8000', '4. close': '23.1750', '5. volume': '7670464'}, '2019-01-22': {'1. open': '22.4400', '2. high': '22.6250', '3. low': '22.3000', '4. close': '22.4550', '5. volume': '3798651'}, '2019-01-21': {'1. open': '22.4750', '2. high': '22.5400', '3. low': '22.3800', '4. close': '22.4500', '5. volume': '1980323'}, '2019-01-18': {'1. open': '22.5000', '2. high': '22.6650', '3. low': '22.4300', '4. close': '22.5550', '5. volume': '5424565'}, '2019-01-17': {'1. open': '22.3550', '2. high': '22.4300', '3. low': '22.2200', '4. close': '22.3550', '5. volume': '2863388'}, '2019-01-16': {'1. open': '22.3850', '2. high': '22.4600', '3. low': '22.1800', '4. close': '22.3350', '5. volume': '3133575'}, '2019-01-15': {'1. open': '22.4450', '2. high': '22.5700', '3. low': '22.1250', '4. close': '22.3100', '5. volume': '3668302'}, '2019-01-14': {'1. open': '22.2900', '2. high': '22.4400', '3. low': '22.1850', '4. close': '22.3800', '5. volume': '3098510'}, '2019-01-11': {'1. open': '22.5200', '2. high': '22.8400', '3. low': '22.3000', '4. close': '22.4200', '5. volume': '4930338'}, '2019-01-10': {'1. open': '22.3750', '2. high': '22.7350', '3. low': '22.3500', '4. close': '22.6100', '5. volume': '3639291'}, '2019-01-09': {'1. open': '22.6700', '2. high': '22.7200', '3. low': '22.3050', '4. close': '22.3950', '5. volume': '3771538'}, '2019-01-08': {'1. open': '22.4450', '2. high': '22.7700', '3. low': '22.3750', '4. close': '22.5850', '5. volume': '4953416'}, '2019-01-07': {'1. open': '22.4100', '2. high': '22.4550', '3. low': '22.1650', '4. close': '22.3750', '5. volume': '3496137'}, '2019-01-04': {'1. open': '22.3000', '2. high': '22.4750', '3. low': '22.0750', '4. close': '22.3400', '5. volume': '3647157'}, '2019-01-03': {'1. open': '22.0850', '2. high': '22.2000', '3. low': '21.8950', '4. close': '22.1550', '5. volume': '3506583'}, '2019-01-02': {'1. open': '22.0150', '2. high': '22.2850', '3. low': '21.5700', '4. close': '22.1100', '5. volume': '2783942'}, '2018-12-31': {'1. open': '22.1400', '2. high': '22.1700', '3. low': '21.9850', '4. close': '22.0750', '5. volume': '766220'}, '2018-12-28': {'1. open': '21.9700', '2. high': '22.1750', '3. low': '21.8950', '4. close': '22.0650', '5. volume': '2700285'}, '2018-12-27': {'1. open': '22.1950', '2. high': '22.2400', '3. low': '21.7700', '4. close': '21.9300', '5. volume': '3544986'}, '2018-12-24': {'1. open': '22.2000', '2. high': '22.2650', '3. low': '21.9850', '4. close': '22.0550', '5. volume': '707029'}, '2018-12-21': {'1. open': '22.2950', '2. high': '22.3500', '3. low': '21.8650', '4. close': '22.3500', '5. volume': '15517702'}, '2018-12-20': {'1. open': '22.2750', '2. high': '22.3850', '3. low': '22.0900', '4. close': '22.3850', '5. volume': '5480479'}, '2018-12-19': {'1. open': '22.1500', '2. high': '22.6950', '3. low': '22.1200', '4. close': '22.4050', '5. volume': '5059713'}, '2018-12-18': {'1. open': '22.4500', '2. high': '22.5250', '3. low': '21.9850', '4. close': '22.0950', '5. volume': '4938718'}, '2018-12-17': {'1. open': '22.6200', '2. high': '22.6700', '3. low': '22.3700', '4. close': '22.3900', '5. volume': '4402802'}, '2018-12-14': {'1. open': '22.3000', '2. high': '22.7500', '3. low': '22.2600', '4. close': '22.6850', '5. volume': '4872144'}, '2018-12-13': {'1. open': '22.7050', '2. high': '22.7800', '3. low': '22.2350', '4. close': '22.3750', '5. volume': '4519517'}, '2018-12-12': {'1. open': '22.4400', '2. high': '22.8500', '3. low': '22.3150', '4. close': '22.6200', '5. volume': '5869504'}, '2018-12-11': {'1. open': '22.0150', '2. high': '22.4000', '3. low': '21.9400', '4. close': '22.2900', '5. volume': '4749493'}, '2018-12-10': {'1. open': '22.1700', '2. high': '22.3300', '3. low': '21.9150', '4. close': '22.0000', '5. volume': '4914773'}, '2018-12-07': {'1. open': '22.1050', '2. high': '22.4400', '3. low': '22.1000', '4. close': '22.1800', '5. volume': '5395083'}, '2018-12-06': {'1. open': '22.3450', '2. high': '22.4650', '3. low': '21.7650', '4. close': '22.0000', '5. volume': '8139180'}, '2018-12-05': {'1. open': '22.5950', '2. high': '22.6950', '3. low': '22.4150', '4. close': '22.4400', '5. volume': '3407745'}, '2018-12-04': {'1. open': '22.4150', '2. high': '22.9400', '3. low': '22.4050', '4. close': '22.7300', '5. volume': '5645022'}, '2018-12-03': {'1. open': '22.7150', '2. high': '23.0350', '3. low': '22.3400', '4. close': '22.4000', '5. volume': '4417602'}, '2018-11-30': {'1. open': '22.4300', '2. high': '22.7900', '3. low': '22.4050', '4. close': '22.7050', '5. volume': '8089255'}, '2018-11-29': {'1. open': '22.8000', '2. high': '22.9100', '3. low': '22.5050', '4. close': '22.5050', '5. volume': '4502671'}, '2018-11-28': {'1. open': '22.6900', '2. high': '22.8500', '3. low': '22.6700', '4. close': '22.6800', '5. volume': '4305582'}, '2018-11-27': {'1. open': '22.6500', '2. high': '22.7750', '3. low': '22.4850', '4. close': '22.6650', '5. volume': '3770474'}, '2018-11-26': {'1. open': '22.5900', '2. high': '22.7750', '3. low': '22.4850', '4. close': '22.6600', '5. volume': '4015275'}, '2018-11-23': {'1. open': '22.4600', '2. high': '22.5750', '3. low': '22.2950', '4. close': '22.5600', '5. volume': '2974370'}, '2018-11-22': {'1. open': '22.4500', '2. high': '22.5650', '3. low': '22.3800', '4. close': '22.4200', '5. volume': '4992396'}, '2018-11-21': {'1. open': '22.5250', '2. high': '22.8350', '3. low': '22.4800', '4. close': '22.5500', '5. volume': '6180728'}, '2018-11-20': {'1. open': '22.8000', '2. high': '22.8450', '3. low': '22.2800', '4. close': '22.3650', '5. volume': '5631341'}, '2018-11-19': {'1. open': '22.8400', '2. high': '23.2600', '3. low': '22.8400', '4. close': '22.8850', '5. volume': '4493106'}, '2018-11-16': {'1. open': '22.8700', '2. high': '23.0700', '3. low': '22.7300', '4. close': '22.8450', '5. volume': '6764828'}, '2018-11-15': {'1. open': '22.9000', '2. high': '23.0650', '3. low': '22.5300', '4. close': '22.8400', '5. volume': '5139509'}, '2018-11-14': {'1. open': '22.7950', '2. high': '23.0900', '3. low': '22.5500', '4. close': '22.8350', '5. volume': '5830547'}, '2018-11-13': {'1. open': '22.5000', '2. high': '23.1250', '3. low': '22.5000', '4. close': '23.1250', '5. volume': '7951750'}, '2018-11-12': {'1. open': '22.5200', '2. high': '22.9650', '3. low': '22.5100', '4. close': '22.5550', '5. volume': '6185077'}, '2018-11-09': {'1. open': '22.1000', '2. high': '22.6350', '3. low': '22.1000', '4. close': '22.6000', '5. volume': '6471492'}, '2018-11-08': {'1. open': '21.6800', '2. high': '22.2150', '3. low': '21.6800', '4. close': '22.1100', '5. volume': '7361346'}, '2018-11-07': {'1. open': '21.1000', '2. high': '21.8950', '3. low': '21.0050', '4. close': '21.8000', '5. volume': '13868640'}, '2018-11-06': {'1. open': '20.4100', '2. high': '20.5050', '3. low': '20.1850', '4. close': '20.3700', '5. volume': '4812073'}, '2018-11-05': {'1. open': '20.3400', '2. high': '20.5200', '3. low': '20.2900', '4. close': '20.3950', '5. volume': '3790524'}, '2018-11-02': {'1. open': '20.3900', '2. high': '20.4950', '3. low': '20.2800', '4. close': '20.3450', '5. volume': '4426042'}, '2018-11-01': {'1. open': '20.1200', '2. high': '20.5400', '3. low': '20.1200', '4. close': '20.2950', '5. volume': '4760428'}, '2018-10-31': {'1. open': '20.2450', '2. high': '20.3900', '3. low': '20.0750', '4. close': '20.2300', '5. volume': '6064116'}, '2018-10-30': {'1. open': '19.8940', '2. high': '20.2500', '3. low': '19.8680', '4. close': '20.1800', '5. volume': '4510743'}, '2018-10-29': {'1. open': '20.0950', '2. high': '20.1850', '3. low': '19.6160', '4. close': '19.8900', '5. volume': '5387349'}, '2018-10-26': {'1. open': '20.3850', '2. high': '20.4450', '3. low': '19.9440', '4. close': '20.1200', '5. volume': '6808676'}, '2018-10-25': {'1. open': '20.4100', '2. high': '20.5150', '3. low': '20.2050', '4. close': '20.5150', '5. volume': '5246059'}, '2018-10-24': {'1. open': '20.3200', '2. high': '20.4800', '3. low': '20.2700', '4. close': '20.2950', '5. volume': '4926684'}, '2018-10-23': {'1. open': '19.9500', '2. high': '20.3350', '3. low': '19.9240', '4. close': '20.2600', '5. volume': '5656476'}, '2018-10-22': {'1. open': '20.1500', '2. high': '20.1900', '3. low': '19.9420', '4. close': '19.9540', '5. volume': '3243220'}, '2018-10-19': {'1. open': '19.9500', '2. high': '20.1100', '3. low': '19.8900', '4. close': '20.0550', '5. volume': '6519851'}, '2018-10-18': {'1. open': '19.6400', '2. high': '20.0400', '3. low': '19.6140', '4. close': '19.9060', '5. volume': '6200347'}, '2018-10-17': {'1. open': '19.5640', '2. high': '19.7900', '3. low': '19.4000', '4. close': '19.4820', '5. volume': '5220704'}, '2018-10-16': {'1. open': '19.6940', '2. high': '19.7740', '3. low': '18.9880', '4. close': '19.5680', '5. volume': '9457169'}, '2018-10-15': {'1. open': '19.2480', '2. high': '19.7680', '3. low': '19.2100', '4. close': '19.6580', '5. volume': '5833548'}, '2018-10-12': {'1. open': '19.2220', '2. high': '19.2480', '3. low': '19.0340', '4. close': '19.1700', '5. volume': '4971561'}, '2018-10-11': {'1. open': '19.5060', '2. high': '19.6660', '3. low': '19.1200', '4. close': '19.1520', '5. volume': '7682448'}, '2018-10-10': {'1. open': '19.4880', '2. high': '19.8280', '3. low': '19.4100', '4. close': '19.5760', '5. volume': '6741736'}, '2018-10-09': {'1. open': '18.9740', '2. high': '19.4880', '3. low': '18.9740', '4. close': '19.3860', '5. volume': '6137518'}, '2018-10-08': {'1. open': '18.9480', '2. high': '18.9940', '3. low': '18.8420', '4. close': '18.9600', '5. volume': '5144341'}, '2018-10-05': {'1. open': '19.0200', '2. high': '19.2020', '3. low': '19.0060', '4. close': '19.0200', '5. volume': '4172205'}, '2018-10-04': {'1. open': '19.3120', '2. high': '19.3120', '3. low': '18.9900', '4. close': '19.0400', '5. volume': '5500493'}, '2018-10-03': {'1. open': '19.3240', '2. high': '19.5200', '3. low': '19.3020', '4. close': '19.3600', '5. volume': '4584741'}, '2018-10-02': {'1. open': '19.3140', '2. high': '19.4040', '3. low': '19.1920', '4. close': '19.3700', '5. volume': '4658888'}, '2018-10-01': {'1. open': '19.7200', '2. high': '19.7520', '3. low': '19.3700', '4. close': '19.3700', '5. volume': '4418937'}, '2018-09-28': {'1. open': '19.7120', '2. high': '19.8640', '3. low': '19.6820', '4. close': '19.7500', '5. volume': '6035966'}, '2018-09-27': {'1. open': '19.5120', '2. high': '19.7160', '3. low': '19.4260', '4. close': '19.7160', '5. volume': '4194743'}, '2018-09-26': {'1. open': '19.4700', '2. high': '19.5960', '3. low': '19.4660', '4. close': '19.5600', '5. volume': '3579751'}, '2018-09-25': {'1. open': '19.4200', '2. high': '19.6020', '3. low': '19.3420', '4. close': '19.4960', '5. volume': '5041470'}, '2018-09-24': {'1. open': '19.2700', '2. high': '19.5180', '3. low': '19.2520', '4. close': '19.4500', '5. volume': '6072056'}, '2018-09-21': {'1. open': '18.9000', '2. high': '19.3180', '3. low': '18.9000', '4. close': '19.3180', '5. volume': '15648107'}, '2018-09-20': {'1. open': '19.1300', '2. high': '19.3140', '3. low': '18.8480', '4. close': '18.9320', '5. volume': '8600313'}, '2018-09-19': {'1. open': '19.4440', '2. high': '19.6280', '3. low': '19.2160', '4. close': '19.2720', '5. volume': '5692878'}, '2018-09-18': {'1. open': '19.7500', '2. high': '19.7600', '3. low': '19.3780', '4. close': '19.4660', '5. volume': '6339305'}, '2018-09-17': {'1. open': '19.4320', '2. high': '20.0350', '3. low': '19.4100', '4. close': '19.7640', '5. volume': '8649230'}, '2018-09-14': {'1. open': '20.2000', '2. high': '20.2000', '3. low': '18.6000', '4. close': '19.5000', '5. volume': '13443413'}, '2018-09-13': {'1. open': '20.9700', '2. high': '21.1650', '3. low': '20.4000', '4. close': '20.4000', '5. volume': '7745685'}, '2018-09-12': {'1. open': '20.8200', '2. high': '21.1050', '3. low': '20.8100', '4. close': '21.0350', '5. volume': '4591378'}}}

In [3]:
data.keys()

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [4]:
with urllib.request.urlopen("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AD.AMS&apikey=SLQLZPOJI7PGOISP") as url:
    data = json.loads(url.read().decode())
    df=pd.DataFrame.from_dict(data['Time Series (Daily)'], orient='index')

In [5]:
df.shape

(100, 5)

In [6]:
df

            1. open  2. high   3. low 4. close 5. volume
2018-09-12  20.8200  21.1050  20.8100  21.0350   4591378
2018-09-13  20.9700  21.1650  20.4000  20.4000   7745685
2018-09-14  20.2000  20.2000  18.6000  19.5000  13443413
2018-09-17  19.4320  20.0350  19.4100  19.7640   8649230
2018-09-18  19.7500  19.7600  19.3780  19.4660   6339305
2018-09-19  19.4440  19.6280  19.2160  19.2720   5692878
2018-09-20  19.1300  19.3140  18.8480  18.9320   8600313
2018-09-21  18.9000  19.3180  18.9000  19.3180  15648107
2018-09-24  19.2700  19.5180  19.2520  19.4500   6072056
2018-09-25  19.4200  19.6020  19.3420  19.4960   5041470
2018-09-26  19.4700  19.5960  19.4660  19.5600   3579751
2018-09-27  19.5120  19.7160  19.4260  19.7160   4194743
2018-09-28  19.7120  19.8640  19.6820  19.7500   6035966
2018-10-01  19.7200  19.7520  19.3700  19.3700   4418937
2018-10-02  19.3140  19.4040  19.1920  19.3700   4658888
2018-10-03  19.3240  19.5200  19.3020  19.3600   4584741
2018-10-04  19.3120  19.3120  18.9900  19.0400   5500493
2018-10-05  19.0200  19.2020  19.0060  19.0200   4172205
2018-10-08  18.9480  18.9940  18.8420  18.9600   5144341
2018-10-09  18.9740  19.4880  18.9740  19.3860   6137518
2018-10-10  19.4880  19.8280  19.4100  19.5760   6741736
2018-10-11  19.5060  19.6660  19.1200  19.1520   7682448
2018-10-12  19.2220  19.2480  19.0340  19.1700   4971561
2018-10-15  19.2480  19.7680  19.2100  19.6580   5833548
2018-10-16  19.6940  19.7740  18.9880  19.5680   9457169
2018-10-17  19.5640  19.7900  19.4000  19.4820   5220704
2018-10-18  19.6400  20.0400  19.6140  19.9060   6200347
2018-10-19  19.9500  20.1100  19.8900  20.0550   6519851
2018-10-22  20.1500  20.1900  19.9420  19.9540   3243220
2018-10-23  19.9500  20.3350  19.9240  20.2600   5656476
...             ...      ...      ...      ...       ...
2018-12-19  22.1500  22.6950  22.1200  22.4050   5059713
2018-12-20  22.2750  22.3850  22.0900  22.3850   5480479
2018-12-21  22.2950  22.3500  21.8650  22.3500  15517702
2018-12-24  22.2000  22.2650  21.9850  22.0550    707029
2018-12-27  22.1950  22.2400  21.7700  21.9300   3544986
2018-12-28  21.9700  22.1750  21.8950  22.0650   2700285
2018-12-31  22.1400  22.1700  21.9850  22.0750    766220
2019-01-02  22.0150  22.2850  21.5700  22.1100   2783942
2019-01-03  22.0850  22.2000  21.8950  22.1550   3506583
2019-01-04  22.3000  22.4750  22.0750  22.3400   3647157
2019-01-07  22.4100  22.4550  22.1650  22.3750   3496137
2019-01-08  22.4450  22.7700  22.3750  22.5850   4953416
2019-01-09  22.6700  22.7200  22.3050  22.3950   3771538
2019-01-10  22.3750  22.7350  22.3500  22.6100   3639291
2019-01-11  22.5200  22.8400  22.3000  22.4200   4930338
2019-01-14  22.2900  22.4400  22.1850  22.3800   3098510
2019-01-15  22.4450  22.5700  22.1250  22.3100   3668302
2019-01-16  22.3850  22.4600  22.1800  22.3350   3133575
2019-01-17  22.3550  22.4300  22.2200  22.3550   2863388
2019-01-18  22.5000  22.6650  22.4300  22.5550   5424565
2019-01-21  22.4750  22.5400  22.3800  22.4500   1980323
2019-01-22  22.4400  22.6250  22.3000  22.4550   3798651
2019-01-23  22.9950  23.2750  22.8000  23.1750   7670464
2019-01-24  23.0700  23.1150  22.8950  23.0750   5334620
2019-01-25  23.1450  23.4750  23.0700  23.3850   4711103
2019-01-28  23.2850  23.3700  23.0950  23.2150   3750427
2019-01-29  23.4000  23.4900  23.3250  23.4000   3138199
2019-01-30  23.4150  23.4200  23.2050  23.3300   3114316
2019-01-31  23.0000  23.1000  22.6550  23.0200   6522780
2019-02-01  23.0900  23.1500  22.8800  22.9450   3522066

[100 rows x 5 columns]

In [9]:
type(df['1. open'])

pandas.core.series.Series